// Code generated by github.com/visvasity/blockgen. DO NOT EDIT.

package output

import (
	"fmt"
	"strings"

	"github.com/visvasity/blockgen/blockgen"
	input "github.com/visvasity/blockgen/input"
)

// Reader type defines accessor methods for read-only access.
type BlockHeaderReader blockgen.BlockBytes

// Writer type extends the reader with mutable methods.
type BlockHeaderWriter struct{ BlockHeaderReader }

var structSizeOfBlockHeader = blockgen.SizeFor[input.BlockHeader]()
var fieldOffsetsOfBlockHeader = blockgen.OffsetsFor[input.BlockHeader](nil)

// BlockBytes returns access to the underlying byte slice.
func (v BlockHeaderReader) BlockBytes() blockgen.BlockBytes {
	return blockgen.BlockBytes(v)
}

// Writer returns the BlockHeader writer for read-write access to it's fields.
func (v BlockHeaderReader) Writer() BlockHeaderWriter {
	return BlockHeaderWriter{v}
}

// Reader returns the BlockHeader reader with read-only access to it's fields.
func (v BlockHeaderWriter) Reader() BlockHeaderReader {
	return v.BlockHeaderReader
}

// IsZero returns true if all underlying bytes are zero.
func (v BlockHeaderReader) IsZero() bool {
	return blockgen.IsZero(v[:structSizeOfBlockHeader])
}

// SetZero sets all underlying bytes to zero.
func (v BlockHeaderWriter) SetZero() {
	blockgen.SetZero(v.BlockBytes()[:structSizeOfBlockHeader])
}

func (v BlockHeaderReader) String() string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "Checksum=[%d]{", v.ChecksumLen())
	for i := 0; i < v.ChecksumLen(); i++ {
		if i == 0 {
			fmt.Fprintf(&sb, "%d", v.ChecksumItemAt(i))
		} else {
			fmt.Fprintf(&sb, " %d", v.ChecksumItemAt(i))
		}
	}
	fmt.Fprintf(&sb, "}")
	fmt.Fprintf(&sb, " ")
	fmt.Fprintf(&sb, "BlockLSN=%d", v.BlockLSN())
	fmt.Fprintf(&sb, " ")
	fmt.Fprintf(&sb, "BlockTypeID=%d", v.BlockTypeID())
	return sb.String()
}

func (v BlockHeaderReader) CopyTo(x *input.BlockHeader) {
	for i := 0; i < v.ChecksumLen(); i++ {
		x.Checksum[i] = v.ChecksumItemAt(i)
	}
	x.BlockLSN = v.BlockLSN()
	x.BlockTypeID = v.BlockTypeID()
}

func (v BlockHeaderWriter) CopyFrom(x *input.BlockHeader) {
	for i := 0; i < v.ChecksumLen(); i++ {
		v.SetChecksumItemAt(i, x.Checksum[i])
	}
	v.SetBlockLSN(x.BlockLSN)
	v.SetBlockTypeID(x.BlockTypeID)
}

func (v BlockHeaderReader) ChecksumLen() int {
	return int(32)
}

func (v BlockHeaderReader) ChecksumItemAt(i int) byte {
	if i < 0 || i >= v.ChecksumLen() {
		panic(fmt.Sprintf("array index %d is out of range [0:%d]", i, v.ChecksumLen()))
	}
	var elemSize = blockgen.ElemSizeFor[[1]byte]()
	var offset = fieldOffsetsOfBlockHeader[0] + i*elemSize
	return byte(v.BlockBytes().Uint8At(offset))
}

func (v BlockHeaderWriter) SetChecksumItemAt(i int, x byte) {
	if i < 0 || i >= v.ChecksumLen() {
		panic(fmt.Sprintf("array index %d is out of range [0:%d]", i, v.ChecksumLen()))
	}
	var elemSize = blockgen.ElemSizeFor[[1]byte]()
	var offset = fieldOffsetsOfBlockHeader[0] + i*elemSize
	v.BlockBytes().SetUint8At(offset, uint8(x))
}

func (v BlockHeaderReader) BlockLSN() input.LSN {
	var offset = fieldOffsetsOfBlockHeader[1]
	return input.LSN(v.BlockBytes().Int64At(offset))
}

func (v BlockHeaderWriter) SetBlockLSN(x input.LSN) {
	var offset = fieldOffsetsOfBlockHeader[1]
	v.BlockBytes().SetInt64At(offset, int64(x))
}

func (v BlockHeaderReader) BlockTypeID() input.BlockType {
	var offset = fieldOffsetsOfBlockHeader[2]
	return input.BlockType(v.BlockBytes().Uint16At(offset))
}

func (v BlockHeaderWriter) SetBlockTypeID(x input.BlockType) {
	var offset = fieldOffsetsOfBlockHeader[2]
	v.BlockBytes().SetUint16At(offset, uint16(x))
}
