// Code generated by github.com/visvasity/blockgen. DO NOT EDIT.

package output

import (
	input "github.com/visvasity/blockgen/input"
)

type (
	BlockType = input.BlockType
	DBA       = input.DBA
	LBA       = input.LBA
	LSN       = input.LSN
	ObjectID  = input.ObjectID
	PBA       = input.PBA
)
