// Code generated by github.com/visvasity/slabgen. DO NOT EDIT.

package output

import (
	"fmt"
	"strings"

	input "github.com/visvasity/slabgen/input"
	"github.com/visvasity/slabgen/slabs"
	"github.com/visvasity/slabgen/slabutil"
)

// Reader type defines accessor methods for read-only access.
type JournalRegionReader []byte

// Writer type extends the reader with mutable methods.
type JournalRegionWriter struct{ JournalRegionReader }

var structSizeOfJournalRegion = slabutil.SizeFor[input.JournalRegion]()
var fieldOffsetsOfJournalRegion = slabutil.OffsetsFor[input.JournalRegion](nil)

// SlabBytes returns access to the underlying byte slice.
func (v JournalRegionReader) SlabBytes() slabs.Bytes {
	return []byte(v)
}

// Writer returns the JournalRegion writer for read-write access to it's fields.
func (v JournalRegionReader) Writer() JournalRegionWriter {
	return JournalRegionWriter{v}
}

// Reader returns the JournalRegion reader with read-only access to it's fields.
func (v JournalRegionWriter) Reader() JournalRegionReader {
	return v.JournalRegionReader
}

// IsZero returns true if all underlying bytes are zero.
func (v JournalRegionReader) IsZero() bool {
	return slabutil.IsZero(v[:structSizeOfJournalRegion])
}

// SetZero sets all underlying bytes to zero.
func (v JournalRegionWriter) SetZero() {
	slabutil.SetZero(v.SlabBytes()[:structSizeOfJournalRegion])
}

func (v JournalRegionReader) String() string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "JournalOffset=%d", v.JournalOffset())
	fmt.Fprintf(&sb, " ")
	fmt.Fprintf(&sb, "FileOffset=%d", v.FileOffset())
	fmt.Fprintf(&sb, " ")
	fmt.Fprintf(&sb, "RegionSize=%d", v.RegionSize())
	return sb.String()
}

func (v JournalRegionReader) CopyTo(x *input.JournalRegion) {
	x.JournalOffset = v.JournalOffset()
	x.FileOffset = v.FileOffset()
	x.RegionSize = v.RegionSize()
}

func (v JournalRegionWriter) CopyFrom(x *input.JournalRegion) {
	v.SetJournalOffset(x.JournalOffset)
	v.SetFileOffset(x.FileOffset)
	v.SetRegionSize(x.RegionSize)
}

func (v JournalRegionReader) JournalOffset() int64 {
	var offset = fieldOffsetsOfJournalRegion[0]
	return int64(v.SlabBytes().Int64At(offset))
}

func (v JournalRegionWriter) SetJournalOffset(x int64) {
	var offset = fieldOffsetsOfJournalRegion[0]
	v.SlabBytes().SetInt64At(offset, int64(x))
}

func (v JournalRegionReader) FileOffset() int64 {
	var offset = fieldOffsetsOfJournalRegion[1]
	return int64(v.SlabBytes().Int64At(offset))
}

func (v JournalRegionWriter) SetFileOffset(x int64) {
	var offset = fieldOffsetsOfJournalRegion[1]
	v.SlabBytes().SetInt64At(offset, int64(x))
}

func (v JournalRegionReader) RegionSize() int64 {
	var offset = fieldOffsetsOfJournalRegion[2]
	return int64(v.SlabBytes().Int64At(offset))
}

func (v JournalRegionWriter) SetRegionSize(x int64) {
	var offset = fieldOffsetsOfJournalRegion[2]
	v.SlabBytes().SetInt64At(offset, int64(x))
}
