// Code generated by github.com/visvasity/blockgen. DO NOT EDIT.

package output

import (
	"fmt"
	"strings"

	"github.com/visvasity/blockgen/blockgen"
	input "github.com/visvasity/blockgen/input"
)

// Reader type defines accessor methods for read-only access.
type TestFinalSliceKind4Reader[T1 blockgen.Number, S1 blockgen.Struct, S1Reader blockgen.Reader[S1, S1Writer], S1Writer blockgen.Writer[S1, S1Reader]] blockgen.BlockBytes

// Writer type extends the reader with mutable methods.
type TestFinalSliceKind4Writer[T1 blockgen.Number, S1 blockgen.Struct, S1Reader blockgen.Reader[S1, S1Writer], S1Writer blockgen.Writer[S1, S1Reader]] struct {
	TestFinalSliceKind4Reader[T1, S1, S1Reader, S1Writer]
}

var fieldOffsetsOfTestFinalSliceKind4 blockgen.OffsetsMap

// BlockBytes returns access to the underlying byte slice.
func (v TestFinalSliceKind4Reader[T1, S1, S1Reader, S1Writer]) BlockBytes() blockgen.BlockBytes {
	return blockgen.BlockBytes(v)
}

// Writer returns the TestFinalSliceKind4 writer for read-write access to it's fields.
func (v TestFinalSliceKind4Reader[T1, S1, S1Reader, S1Writer]) Writer() TestFinalSliceKind4Writer[T1, S1, S1Reader, S1Writer] {
	return TestFinalSliceKind4Writer[T1, S1, S1Reader, S1Writer]{v}
}

// Reader returns the TestFinalSliceKind4 reader with read-only access to it's fields.
func (v TestFinalSliceKind4Writer[T1, S1, S1Reader, S1Writer]) Reader() TestFinalSliceKind4Reader[T1, S1, S1Reader, S1Writer] {
	return v.TestFinalSliceKind4Reader
}

// IsZero returns true if all underlying bytes are zero.
func (v TestFinalSliceKind4Reader[T1, S1, S1Reader, S1Writer]) IsZero() bool {
	var structSizeOfTestFinalSliceKind4 = blockgen.SizeFor[input.TestFinalSliceKind4[T1, S1]]()
	return blockgen.IsZero(v[:structSizeOfTestFinalSliceKind4])
}

// SetZero sets all underlying bytes to zero.
func (v TestFinalSliceKind4Writer[T1, S1, S1Reader, S1Writer]) SetZero() {
	var structSizeOfTestFinalSliceKind4 = blockgen.SizeFor[input.TestFinalSliceKind4[T1, S1]]()
	blockgen.SetZero(v.BlockBytes()[:structSizeOfTestFinalSliceKind4])
}

func (v TestFinalSliceKind4Reader[T1, S1, S1Reader, S1Writer]) String() string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "FinalSlice=[:%d:%d]{", v.FinalSliceLen(), v.FinalSliceCap())
	for i := 0; i < v.FinalSliceLen(); i++ {
		if i == 0 {
			fmt.Fprintf(&sb, "{%v}", v.FinalSliceItemAt(i))
		} else {
			fmt.Fprintf(&sb, " {%v}", v.FinalSliceItemAt(i))
		}
	}
	fmt.Fprintf(&sb, "}")
	return sb.String()
}

func (v TestFinalSliceKind4Reader[T1, S1, S1Reader, S1Writer]) CopyTo(x *input.TestFinalSliceKind4[T1, S1]) {
	x.FinalSlice = make([]S1, v.FinalSliceLen())
	for i := 0; i < v.FinalSliceLen(); i++ {
		v.FinalSliceItemAt(i).CopyTo(&x.FinalSlice[i])
	}
}

func (v TestFinalSliceKind4Writer[T1, S1, S1Reader, S1Writer]) CopyFrom(x *input.TestFinalSliceKind4[T1, S1]) {
	v.ResizeFinalSlice(len(x.FinalSlice))
	for i := 0; i < len(x.FinalSlice); i++ {
		v.FinalSliceItemAt(i).Writer().CopyFrom(&x.FinalSlice[i])
	}
}

// TestFinalSliceKind4SliceFieldCap returns the slice field capacity for the given underlying byte slice size.
func TestFinalSliceKind4SliceFieldCap[T1 blockgen.Number, S1 blockgen.Struct](nbytes int) int {
	var structSizeOfTestFinalSliceKind4 = blockgen.SizeFor[input.TestFinalSliceKind4[T1, S1]]()
	var sliceElemSizeOfTestFinalSliceKind4 = blockgen.ElemSizeFor[S1]()
	// TODO: We should also add the required alignment offset to the struct-size.
	return (nbytes - structSizeOfTestFinalSliceKind4) / sliceElemSizeOfTestFinalSliceKind4
}

// FinalSliceLen method returns number of elements in the slice field.
func (v TestFinalSliceKind4Reader[T1, S1, S1Reader, S1Writer]) FinalSliceLen() int {
	var fieldOffsetsOfTestFinalSliceKind4 = blockgen.OffsetsFor[input.TestFinalSliceKind4[T1, S1]](&fieldOffsetsOfTestFinalSliceKind4)
	var offset = fieldOffsetsOfTestFinalSliceKind4[0] + blockgen.OffsetOfSliceLen
	return blockgen.IntAt(v.BlockBytes(), offset)
}

func (v TestFinalSliceKind4Writer[T1, S1, S1Reader, S1Writer]) internalSetFinalSliceLen(x int) {
	var fieldOffsetsOfTestFinalSliceKind4 = blockgen.OffsetsFor[input.TestFinalSliceKind4[T1, S1]](&fieldOffsetsOfTestFinalSliceKind4)
	var offset = fieldOffsetsOfTestFinalSliceKind4[0] + blockgen.OffsetOfSliceLen
	blockgen.SetIntAt(v.BlockBytes(), offset, x)
}

// FinalSliceCap method returns maximum number of elements for the slice field.
func (v TestFinalSliceKind4Reader[T1, S1, S1Reader, S1Writer]) FinalSliceCap() int {
	var fieldOffsetsOfTestFinalSliceKind4 = blockgen.OffsetsFor[input.TestFinalSliceKind4[T1, S1]](&fieldOffsetsOfTestFinalSliceKind4)
	var offset = fieldOffsetsOfTestFinalSliceKind4[0] + blockgen.OffsetOfSliceCap
	return blockgen.IntAt(v.BlockBytes(), offset)
}

func (v TestFinalSliceKind4Writer[T1, S1, S1Reader, S1Writer]) internalSetFinalSliceCap(x int) {
	var fieldOffsetsOfTestFinalSliceKind4 = blockgen.OffsetsFor[input.TestFinalSliceKind4[T1, S1]](&fieldOffsetsOfTestFinalSliceKind4)
	var offset = fieldOffsetsOfTestFinalSliceKind4[0] + blockgen.OffsetOfSliceCap
	blockgen.SetIntAt(v.BlockBytes(), offset, x)
}

func (v TestFinalSliceKind4Writer[T1, S1, S1Reader, S1Writer]) ResizeFinalSlice(size int) int {
	if cap := v.FinalSliceCap(); size > cap {
		size = cap
	}
	n := v.FinalSliceLen()
	if size == n {
		return size
	}
	if size < n {
		v.DeleteFinalSliceItems(size, n)
		return size
	}
	v.internalSetFinalSliceLen(size)
	var structSizeOfTestFinalSliceKind4 = blockgen.SizeFor[input.TestFinalSliceKind4[T1, S1]]()
	var elemSize = blockgen.ElemSizeFor[[]S1]()
	var begin = structSizeOfTestFinalSliceKind4 + n*elemSize
	var end = structSizeOfTestFinalSliceKind4 + size*elemSize
	blockgen.SetZero(v.BlockBytes()[begin:end])
	return size
}

func (v TestFinalSliceKind4Writer[T1, S1, S1Reader, S1Writer]) DeleteFinalSliceItems(i, j int) {
	n := v.FinalSliceLen()
	if i < 0 || i >= n {
		panic(fmt.Sprintf("first slice index %d is out of range [0:%d:%d]", i, v.FinalSliceLen(), v.FinalSliceCap()))
	}
	if j < 0 || j >= n {
		panic(fmt.Sprintf("second slice index %d is out of range [0:%d:%d]", i, v.FinalSliceLen(), v.FinalSliceCap()))
	}
	if j < i {
		panic(fmt.Sprintf("invalid slice indices %d < %d", j, i))
	}
	if i == j {
		return
	}
	var structSizeOfTestFinalSliceKind4 = blockgen.SizeFor[input.TestFinalSliceKind4[T1, S1]]()
	var elemSize = blockgen.ElemSizeFor[[]S1]()

	ioff := structSizeOfTestFinalSliceKind4 + i*elemSize
	joff := structSizeOfTestFinalSliceKind4 + j*elemSize
	end := structSizeOfTestFinalSliceKind4 + n*elemSize

	copy(v.BlockBytes()[ioff:end], v.BlockBytes()[joff:end])
	blockgen.SetZero(v.BlockBytes()[end-(joff-ioff) : end])
	v.internalSetFinalSliceLen(n - (j - i))
}

func (v TestFinalSliceKind4Reader[T1, S1, S1Reader, S1Writer]) FinalSliceItemAt(i int) S1Reader {
	if i < 0 || i >= v.FinalSliceLen() {
		panic(fmt.Sprintf("slice index %d is out of range [:%d:%d]", i, v.FinalSliceLen(), v.FinalSliceCap()))
	}
	var structSizeOfTestFinalSliceKind4 = blockgen.SizeFor[input.TestFinalSliceKind4[T1, S1]]()
	var elemSize = blockgen.ElemSizeFor[[]S1]()
	var offset = structSizeOfTestFinalSliceKind4 + i*elemSize
	return S1Reader(v.BlockBytes()[offset:])
}

func (v TestFinalSliceKind4Writer[T1, S1, S1Reader, S1Writer]) SetFinalSliceItemAt(i int, x S1Reader) {
	if i < 0 || i >= v.FinalSliceLen() {
		panic(fmt.Sprintf("slice index %d is out of range [:%d:%d]", i, v.FinalSliceLen(), v.FinalSliceCap()))
	}
	var structSizeOfTestFinalSliceKind4 = blockgen.SizeFor[input.TestFinalSliceKind4[T1, S1]]()
	var elemSize = blockgen.ElemSizeFor[[]S1]()
	var offset = structSizeOfTestFinalSliceKind4 + i*elemSize
	copy(v.BlockBytes()[offset:offset+elemSize], x.BlockBytes()[:elemSize])
}

func (v TestFinalSliceKind4Writer[T1, S1, S1Reader, S1Writer]) AppendFinalSliceItem(x S1Reader) {
	n := v.FinalSliceLen()
	if n == v.FinalSliceCap() {
		panic(fmt.Sprintf("append to slice overflows the maximum capacity [::%d]", v.FinalSliceCap()))
	}
	v.internalSetFinalSliceLen(n + 1)
	var structSizeOfTestFinalSliceKind4 = blockgen.SizeFor[input.TestFinalSliceKind4[T1, S1]]()
	var elemSize = blockgen.ElemSizeFor[[]S1]()
	var offset = structSizeOfTestFinalSliceKind4 + n*elemSize
	if x == nil {
		blockgen.SetZero(v.BlockBytes()[offset : offset+elemSize])
	} else {
		copy(v.BlockBytes()[offset:offset+elemSize], x.BlockBytes()[:elemSize])
	}
}

// NewTestFinalSliceKind4Reader creates a zero-initialized TestFinalSliceKind4. Returns nil if input block size is too small.
func NewTestFinalSliceKind4[T1 blockgen.Number, S1 blockgen.Struct, S1Reader blockgen.Reader[S1, S1Writer], S1Writer blockgen.Writer[S1, S1Reader]](block []byte) TestFinalSliceKind4Reader[T1, S1, S1Reader, S1Writer] {
	var structSizeOfTestFinalSliceKind4 = blockgen.SizeFor[input.TestFinalSliceKind4[T1, S1]]()
	size := len(block)
	if size < structSizeOfTestFinalSliceKind4 {
		return nil
	}
	blockgen.SetZero(block)
	v := TestFinalSliceKind4Reader[T1, S1, S1Reader, S1Writer](block)
	// TestFinalSliceKind4 type has a slice field; we must set a cap on it.
	n := TestFinalSliceKind4SliceFieldCap[T1, S1](size)
	v.Writer().internalSetFinalSliceCap(n)
	return v
}

// OpenTestFinalSliceKind4Reader parses and prepares an existing TestFinalSliceKind4 for read/write access.
func OpenTestFinalSliceKind4[T1 blockgen.Number, S1 blockgen.Struct, S1Reader blockgen.Reader[S1, S1Writer], S1Writer blockgen.Writer[S1, S1Reader]](block []byte) (TestFinalSliceKind4Reader[T1, S1, S1Reader, S1Writer], error) {
	var structSizeOfTestFinalSliceKind4 = blockgen.SizeFor[input.TestFinalSliceKind4[T1, S1]]()
	size := len(block)
	if size < structSizeOfTestFinalSliceKind4 {
		return nil, fmt.Errorf("input size is too small")
	}
	v := TestFinalSliceKind4Reader[T1, S1, S1Reader, S1Writer](block)
	// TestFinalSliceKind4 type has a slice field; validate it's len and cap.
	n := TestFinalSliceKind4SliceFieldCap[T1, S1](size)
	if x := v.FinalSliceCap(); x != n {
		return nil, fmt.Errorf("slice field cap must be %d, found %d", n, x)
	}
	if x := v.FinalSliceLen(); x < 0 || x > n {
		return nil, fmt.Errorf("slice field len is %d, must be between [%d-%d)", x, 0, n)
	}
	return v, nil
}
