// Code generated by github.com/visvasity/blockgen. DO NOT EDIT.

package output

import (
	"fmt"
	"strings"

	"github.com/visvasity/blockgen/blockgen"
	input "github.com/visvasity/blockgen/input"
)

// Reader type defines accessor methods for read-only access.
type TestFinalSliceKind2Reader[T1 blockgen.Number, S1 blockgen.Struct, S1Reader blockgen.Reader[S1, S1Writer], S1Writer blockgen.Writer[S1, S1Reader]] blockgen.BlockBytes

// Writer type extends the reader with mutable methods.
type TestFinalSliceKind2Writer[T1 blockgen.Number, S1 blockgen.Struct, S1Reader blockgen.Reader[S1, S1Writer], S1Writer blockgen.Writer[S1, S1Reader]] struct {
	TestFinalSliceKind2Reader[T1, S1, S1Reader, S1Writer]
}

var fieldOffsetsOfTestFinalSliceKind2 blockgen.OffsetsMap

// BlockBytes returns access to the underlying byte slice.
func (v TestFinalSliceKind2Reader[T1, S1, S1Reader, S1Writer]) BlockBytes() blockgen.BlockBytes {
	return blockgen.BlockBytes(v)
}

// Writer returns the TestFinalSliceKind2 writer for read-write access to it's fields.
func (v TestFinalSliceKind2Reader[T1, S1, S1Reader, S1Writer]) Writer() TestFinalSliceKind2Writer[T1, S1, S1Reader, S1Writer] {
	return TestFinalSliceKind2Writer[T1, S1, S1Reader, S1Writer]{v}
}

// Reader returns the TestFinalSliceKind2 reader with read-only access to it's fields.
func (v TestFinalSliceKind2Writer[T1, S1, S1Reader, S1Writer]) Reader() TestFinalSliceKind2Reader[T1, S1, S1Reader, S1Writer] {
	return v.TestFinalSliceKind2Reader
}

// IsZero returns true if all underlying bytes are zero.
func (v TestFinalSliceKind2Reader[T1, S1, S1Reader, S1Writer]) IsZero() bool {
	var structSizeOfTestFinalSliceKind2 = blockgen.SizeFor[input.TestFinalSliceKind2[T1, S1]]()
	return blockgen.IsZero(v[:structSizeOfTestFinalSliceKind2])
}

// SetZero sets all underlying bytes to zero.
func (v TestFinalSliceKind2Writer[T1, S1, S1Reader, S1Writer]) SetZero() {
	var structSizeOfTestFinalSliceKind2 = blockgen.SizeFor[input.TestFinalSliceKind2[T1, S1]]()
	blockgen.SetZero(v.BlockBytes()[:structSizeOfTestFinalSliceKind2])
}

func (v TestFinalSliceKind2Reader[T1, S1, S1Reader, S1Writer]) String() string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "FinalSlice=[:%d:%d]{", v.FinalSliceLen(), v.FinalSliceCap())
	for i := 0; i < v.FinalSliceLen(); i++ {
		if i == 0 {
			fmt.Fprintf(&sb, "%d", v.FinalSliceItemAt(i))
		} else {
			fmt.Fprintf(&sb, " %d", v.FinalSliceItemAt(i))
		}
	}
	fmt.Fprintf(&sb, "}")
	return sb.String()
}

func (v TestFinalSliceKind2Reader[T1, S1, S1Reader, S1Writer]) CopyTo(x *input.TestFinalSliceKind2[T1, S1]) {
	x.FinalSlice = make([]input.TestNamedInt64, v.FinalSliceLen())
	for i := 0; i < v.FinalSliceLen(); i++ {
		x.FinalSlice[i] = v.FinalSliceItemAt(i)
	}
}

func (v TestFinalSliceKind2Writer[T1, S1, S1Reader, S1Writer]) CopyFrom(x *input.TestFinalSliceKind2[T1, S1]) {
	v.ResizeFinalSlice(len(x.FinalSlice))
	for i := 0; i < len(x.FinalSlice); i++ {
		v.SetFinalSliceItemAt(i, x.FinalSlice[i])
	}
}

// TestFinalSliceKind2SliceFieldCap returns the slice field capacity for the given underlying byte slice size.
func TestFinalSliceKind2SliceFieldCap[T1 blockgen.Number, S1 blockgen.Struct](nbytes int) int {
	var structSizeOfTestFinalSliceKind2 = blockgen.SizeFor[input.TestFinalSliceKind2[T1, S1]]()
	var sliceElemSizeOfTestFinalSliceKind2 = blockgen.ElemSizeFor[input.TestNamedInt64]()
	// TODO: We should also add the required alignment offset to the struct-size.
	return (nbytes - structSizeOfTestFinalSliceKind2) / sliceElemSizeOfTestFinalSliceKind2
}

// FinalSliceLen method returns number of elements in the slice field.
func (v TestFinalSliceKind2Reader[T1, S1, S1Reader, S1Writer]) FinalSliceLen() int {
	var fieldOffsetsOfTestFinalSliceKind2 = blockgen.OffsetsFor[input.TestFinalSliceKind2[T1, S1]](&fieldOffsetsOfTestFinalSliceKind2)
	var offset = fieldOffsetsOfTestFinalSliceKind2[0] + blockgen.OffsetOfSliceLen
	return blockgen.IntAt(v.BlockBytes(), offset)
}

func (v TestFinalSliceKind2Writer[T1, S1, S1Reader, S1Writer]) internalSetFinalSliceLen(x int) {
	var fieldOffsetsOfTestFinalSliceKind2 = blockgen.OffsetsFor[input.TestFinalSliceKind2[T1, S1]](&fieldOffsetsOfTestFinalSliceKind2)
	var offset = fieldOffsetsOfTestFinalSliceKind2[0] + blockgen.OffsetOfSliceLen
	blockgen.SetIntAt(v.BlockBytes(), offset, x)
}

// FinalSliceCap method returns maximum number of elements for the slice field.
func (v TestFinalSliceKind2Reader[T1, S1, S1Reader, S1Writer]) FinalSliceCap() int {
	var fieldOffsetsOfTestFinalSliceKind2 = blockgen.OffsetsFor[input.TestFinalSliceKind2[T1, S1]](&fieldOffsetsOfTestFinalSliceKind2)
	var offset = fieldOffsetsOfTestFinalSliceKind2[0] + blockgen.OffsetOfSliceCap
	return blockgen.IntAt(v.BlockBytes(), offset)
}

func (v TestFinalSliceKind2Writer[T1, S1, S1Reader, S1Writer]) internalSetFinalSliceCap(x int) {
	var fieldOffsetsOfTestFinalSliceKind2 = blockgen.OffsetsFor[input.TestFinalSliceKind2[T1, S1]](&fieldOffsetsOfTestFinalSliceKind2)
	var offset = fieldOffsetsOfTestFinalSliceKind2[0] + blockgen.OffsetOfSliceCap
	blockgen.SetIntAt(v.BlockBytes(), offset, x)
}

func (v TestFinalSliceKind2Writer[T1, S1, S1Reader, S1Writer]) ResizeFinalSlice(size int) int {
	if cap := v.FinalSliceCap(); size > cap {
		size = cap
	}
	n := v.FinalSliceLen()
	if size == n {
		return size
	}
	if size < n {
		v.DeleteFinalSliceItems(size, n)
		return size
	}
	v.internalSetFinalSliceLen(size)
	var structSizeOfTestFinalSliceKind2 = blockgen.SizeFor[input.TestFinalSliceKind2[T1, S1]]()
	var elemSize = blockgen.ElemSizeFor[[]input.TestNamedInt64]()
	var begin = structSizeOfTestFinalSliceKind2 + n*elemSize
	var end = structSizeOfTestFinalSliceKind2 + size*elemSize
	blockgen.SetZero(v.BlockBytes()[begin:end])
	return size
}

func (v TestFinalSliceKind2Writer[T1, S1, S1Reader, S1Writer]) DeleteFinalSliceItems(i, j int) {
	n := v.FinalSliceLen()
	if i < 0 || i >= n {
		panic(fmt.Sprintf("first slice index %d is out of range [0:%d:%d]", i, v.FinalSliceLen(), v.FinalSliceCap()))
	}
	if j < 0 || j >= n {
		panic(fmt.Sprintf("second slice index %d is out of range [0:%d:%d]", i, v.FinalSliceLen(), v.FinalSliceCap()))
	}
	if j < i {
		panic(fmt.Sprintf("invalid slice indices %d < %d", j, i))
	}
	if i == j {
		return
	}
	var structSizeOfTestFinalSliceKind2 = blockgen.SizeFor[input.TestFinalSliceKind2[T1, S1]]()
	var elemSize = blockgen.ElemSizeFor[[]input.TestNamedInt64]()

	ioff := structSizeOfTestFinalSliceKind2 + i*elemSize
	joff := structSizeOfTestFinalSliceKind2 + j*elemSize
	end := structSizeOfTestFinalSliceKind2 + n*elemSize

	copy(v.BlockBytes()[ioff:end], v.BlockBytes()[joff:end])
	blockgen.SetZero(v.BlockBytes()[end-(joff-ioff) : end])
	v.internalSetFinalSliceLen(n - (j - i))
}

func (v TestFinalSliceKind2Reader[T1, S1, S1Reader, S1Writer]) FinalSliceItemAt(i int) input.TestNamedInt64 {
	if i < 0 || i >= v.FinalSliceLen() {
		panic(fmt.Sprintf("slice index %d is out of range [:%d:%d]", i, v.FinalSliceLen(), v.FinalSliceCap()))
	}
	var structSizeOfTestFinalSliceKind2 = blockgen.SizeFor[input.TestFinalSliceKind2[T1, S1]]()
	var elemSize = blockgen.ElemSizeFor[[]input.TestNamedInt64]()
	var offset = structSizeOfTestFinalSliceKind2 + i*elemSize
	return input.TestNamedInt64(v.BlockBytes().Int64At(offset))
}

func (v TestFinalSliceKind2Writer[T1, S1, S1Reader, S1Writer]) SetFinalSliceItemAt(i int, x input.TestNamedInt64) {
	if i < 0 || i >= v.FinalSliceLen() {
		panic(fmt.Sprintf("slice index %d is out of range [:%d:%d]", i, v.FinalSliceLen(), v.FinalSliceCap()))
	}
	var structSizeOfTestFinalSliceKind2 = blockgen.SizeFor[input.TestFinalSliceKind2[T1, S1]]()
	var elemSize = blockgen.ElemSizeFor[[]input.TestNamedInt64]()
	var offset = structSizeOfTestFinalSliceKind2 + i*elemSize
	v.BlockBytes().SetInt64At(offset, int64(x))
}

func (v TestFinalSliceKind2Writer[T1, S1, S1Reader, S1Writer]) AppendFinalSliceItem(x input.TestNamedInt64) {
	n := v.FinalSliceLen()
	if n == v.FinalSliceCap() {
		panic(fmt.Sprintf("append to slice overflows the maximum capacity [::%d]", v.FinalSliceCap()))
	}
	v.internalSetFinalSliceLen(n + 1)
	var structSizeOfTestFinalSliceKind2 = blockgen.SizeFor[input.TestFinalSliceKind2[T1, S1]]()
	var elemSize = blockgen.ElemSizeFor[[]input.TestNamedInt64]()
	var offset = structSizeOfTestFinalSliceKind2 + n*elemSize
	v.BlockBytes().SetInt64At(offset, int64(x))
}

// NewTestFinalSliceKind2Reader creates a zero-initialized TestFinalSliceKind2. Returns nil if input block size is too small.
func NewTestFinalSliceKind2[T1 blockgen.Number, S1 blockgen.Struct, S1Reader blockgen.Reader[S1, S1Writer], S1Writer blockgen.Writer[S1, S1Reader]](block []byte) TestFinalSliceKind2Reader[T1, S1, S1Reader, S1Writer] {
	var structSizeOfTestFinalSliceKind2 = blockgen.SizeFor[input.TestFinalSliceKind2[T1, S1]]()
	size := len(block)
	if size < structSizeOfTestFinalSliceKind2 {
		return nil
	}
	blockgen.SetZero(block)
	v := TestFinalSliceKind2Reader[T1, S1, S1Reader, S1Writer](block)
	// TestFinalSliceKind2 type has a slice field; we must set a cap on it.
	n := TestFinalSliceKind2SliceFieldCap[T1, S1](size)
	v.Writer().internalSetFinalSliceCap(n)
	return v
}

// OpenTestFinalSliceKind2Reader parses and prepares an existing TestFinalSliceKind2 for read/write access.
func OpenTestFinalSliceKind2[T1 blockgen.Number, S1 blockgen.Struct, S1Reader blockgen.Reader[S1, S1Writer], S1Writer blockgen.Writer[S1, S1Reader]](block []byte) (TestFinalSliceKind2Reader[T1, S1, S1Reader, S1Writer], error) {
	var structSizeOfTestFinalSliceKind2 = blockgen.SizeFor[input.TestFinalSliceKind2[T1, S1]]()
	size := len(block)
	if size < structSizeOfTestFinalSliceKind2 {
		return nil, fmt.Errorf("input size is too small")
	}
	v := TestFinalSliceKind2Reader[T1, S1, S1Reader, S1Writer](block)
	// TestFinalSliceKind2 type has a slice field; validate it's len and cap.
	n := TestFinalSliceKind2SliceFieldCap[T1, S1](size)
	if x := v.FinalSliceCap(); x != n {
		return nil, fmt.Errorf("slice field cap must be %d, found %d", n, x)
	}
	if x := v.FinalSliceLen(); x < 0 || x > n {
		return nil, fmt.Errorf("slice field len is %d, must be between [%d-%d)", x, 0, n)
	}
	return v, nil
}
