// Code generated by github.com/visvasity/slabgen. DO NOT EDIT.

package output

import (
	"fmt"
	"strings"

	input "github.com/visvasity/slabgen/input"
	"github.com/visvasity/slabgen/slabs"
	"github.com/visvasity/slabgen/slabutil"
)

// Reader type defines accessor methods for read-only access.
type TestStructReader []byte

// Writer type extends the reader with mutable methods.
type TestStructWriter struct{ TestStructReader }

var structSizeOfTestStruct = slabutil.SizeFor[input.TestStruct]()
var fieldOffsetsOfTestStruct = slabutil.OffsetsFor[input.TestStruct](nil)

// SlabBytes returns access to the underlying byte slice.
func (v TestStructReader) SlabBytes() slabs.Bytes {
	return []byte(v)
}

// Writer returns the TestStruct writer for read-write access to it's fields.
func (v TestStructReader) Writer() TestStructWriter {
	return TestStructWriter{v}
}

// Reader returns the TestStruct reader with read-only access to it's fields.
func (v TestStructWriter) Reader() TestStructReader {
	return v.TestStructReader
}

// IsZero returns true if all underlying bytes are zero.
func (v TestStructReader) IsZero() bool {
	return slabutil.IsZero(v[:structSizeOfTestStruct])
}

// SetZero sets all underlying bytes to zero.
func (v TestStructWriter) SetZero() {
	slabutil.SetZero(v.SlabBytes()[:structSizeOfTestStruct])
}

func (v TestStructReader) String() string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "Int64=%d", v.Int64())
	return sb.String()
}

func (v TestStructReader) CopyTo(x *input.TestStruct) {
	x.Int64 = v.Int64()
}

func (v TestStructWriter) CopyFrom(x *input.TestStruct) {
	v.SetInt64(x.Int64)
}

func (v TestStructReader) Int64() int64 {
	var offset = fieldOffsetsOfTestStruct[0]
	return int64(v.SlabBytes().Int64At(offset))
}

func (v TestStructWriter) SetInt64(x int64) {
	var offset = fieldOffsetsOfTestStruct[0]
	v.SlabBytes().SetInt64At(offset, int64(x))
}
