// Code generated by github.com/visvasity/blockgen. DO NOT EDIT.

package blocks

import (
	blktypes "github.com/visvasity/blockgen/blktypes"
)

type (
	BlockType = blktypes.BlockType
	DBA       = blktypes.DBA
	LSN       = blktypes.LSN
	ObjectID  = blktypes.ObjectID
	PBA       = blktypes.PBA
)
